import 'dart:async';
import 'package:flutter/widgets.dart';
import 'package:flutter_background_service/flutter_background_service.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:ai_pt/src/ai_features/chat_messenger.dart';

class NotificationManager {
  static final _notifications = FlutterLocalNotificationsPlugin();
  static const _channelId = 'chatgpt_background_channel';
  static const _channelName = 'ChatGPT Background Service';

  static Future<void> initializeService() async {
    final service = FlutterBackgroundService();
    await service.configure(
      androidConfiguration: AndroidConfiguration(
        onStart: _onServiceStart,
        autoStart: true,
        isForegroundMode: false,
      ),
      iosConfiguration: IosConfiguration(
        autoStart: false,
        onForeground: (_) async {},
        onBackground: (_) async => true,
      ),
    );
    service.startService();
  }

  @pragma('vm:entry-point')
  static Future<void> _onServiceStart(ServiceInstance service) async {
    WidgetsFlutterBinding.ensureInitialized();
    await dotenv.load(fileName: ".env");

    const androidInit = AndroidInitializationSettings('ic_notification');
    await _notifications.initialize(
      const InitializationSettings(android: androidInit),
    );

    const channel = AndroidNotificationChannel(
      _channelId,
      _channelName,
      description: 'Notifications generated by ChatGPT',
      importance: Importance.low,
    );
    await _notifications.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()?.createNotificationChannel(channel);

    if (service is AndroidServiceInstance) {
      service.setForegroundNotificationInfo(
        title: '🤖 ChatGPT Service',
        content: 'Waiting for tips…',
      );
      await service.setAsForegroundService();
    }

    Timer.periodic(const Duration(minutes: 1), (_) async {
      final msg = await CustomAssistantService().getNotificationMessage();
      if (msg.isNotEmpty) {
        await _notifications.show(
          0,
          '🤖 ChatGPT Tip',
          msg,
          NotificationDetails(
            android: AndroidNotificationDetails(
              _channelId,
              _channelName,
              channelDescription: 'Notifications generated by ChatGPT',
              importance: Importance.max,
              priority: Priority.high,
            ),
          ),
        );
      }
    });
  }
}
